use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use colored::Colorize;

use crate::errors::CliError;

/// ~/.phantom — root directory for all local engine state.
fn phantom_home() -> Result<PathBuf, CliError> {
    dirs::home_dir()
        .map(|h| h.join(".phantom"))
        .ok_or_else(|| CliError::Setup("could not determine home directory".to_string()))
}

/// `phantom setup init` — bootstraps the local environment.
///
/// Creates the directory tree, generates secure keys, and writes a
/// starter .env so the user can `phantom ping` immediately after.
pub fn run_init(project_root: &Path) -> Result<(), CliError> {
    let home = phantom_home()?;

    let dirs_to_create = [
        home.join("sessions"),
        home.join("snapshots"),
        home.join("logs"),
    ];

    for dir in &dirs_to_create {
        if dir.exists() {
            println!("  {} {}", "exists".dimmed(), dir.display());
        } else {
            fs::create_dir_all(dir)?;
            // 0o700 — only the owning user can read session data
            fs::set_permissions(dir, fs::Permissions::from_mode(0o700))?;
            println!("  {} {}", "created".green(), dir.display());
        }
    }

    let env_path = project_root.join(".env");
    if env_path.exists() {
        println!(
            "\n  {} .env already exists at {}",
            "skip".yellow(),
            env_path.display()
        );
        println!("  Run {} to verify your config.", "ph setup doctor".bold());
    } else {
        // Two v4 UUIDs concatenated = 256 bits of CSPRNG entropy via getrandom
        let snapshot_key = format!(
            "{}{}",
            uuid::Uuid::new_v4().simple(),
            uuid::Uuid::new_v4().simple()
        );
        let api_key = uuid::Uuid::new_v4().to_string();

        let env_content = format!(
            r#"# Phantom Engine — generated by `phantom setup init`

PHANTOM_API_KEY={api_key}
PHANTOM_BIND_ADDR=127.0.0.1:8080
PHANTOM_SNAPSHOT_KEY={snapshot_key}
PHANTOM_STORAGE_DIR={storage_dir}
RUST_LOG=phantom=info,tower_http=warn
PHANTOM_LOG_FORMAT=json

PHANTOM_SESSION_LIMIT=1000
PHANTOM_RATE_LIMIT=100

PHANTOM_QUICKJS_POOL_SIZE=10
PHANTOM_V8_POOL_SIZE=5
"#,
            storage_dir = home.join("sessions").display(),
        );

        fs::write(&env_path, env_content)?;
        println!("\n  {} {}", "wrote".green(), env_path.display());
    }

    println!("\n{}", "  Setup complete.".green().bold());
    Ok(())
}

/// `phantom setup doctor` — validates that the environment is correctly configured.
pub fn run_doctor(project_root: &Path) -> Result<(), CliError> {
    let home = phantom_home()?;
    let mut issues: u32 = 0;

    let required_dirs = ["sessions", "snapshots", "logs"];
    for name in &required_dirs {
        let dir = home.join(name);
        if dir.is_dir() {
            println!("  {} ~/.phantom/{}", "✓".green(), name);
        } else {
            println!("  {} ~/.phantom/{} missing", "✗".red(), name);
            issues += 1;
        }
    }

    let env_path = project_root.join(".env");
    if env_path.is_file() {
        println!("  {} .env", "✓".green());
    } else {
        println!("  {} .env not found — run `phantom setup init`", "✗".red());
        issues += 1;
    }

    let required_vars = ["PHANTOM_API_KEY", "PHANTOM_BIND_ADDR"];
    for var in &required_vars {
        match std::env::var(var) {
            Ok(val) if !val.is_empty() => {
                println!("  {} {} is set", "✓".green(), var);
            }
            _ => {
                println!("  {} {} is not set", "✗".red(), var);
                issues += 1;
            }
        }
    }

    if issues == 0 {
        println!("\n  {}", "All checks passed.".green().bold());
    } else {
        println!(
            "\n  {} {} issue(s) found. Run `ph setup init` to fix.",
            "⚠".yellow(),
            issues
        );
    }

    Ok(())
}
