use axum::http::StatusCode;
use phantom_core::JS_EVAL_TIMEOUT_MS;
use serde_json::{json, Value};
use std::sync::atomic::Ordering as AtomicOrdering;
use std::time::Duration;

use crate::engine::EngineAdapter;
use crate::metrics;
use tracing::Instrument;

#[derive(Debug, serde::Deserialize)]
struct EvaluateParams {
    pub script: String,
    pub timeout_ms: Option<u64>,
}

/// Map a `serde_json::Value` to the JSON type name string.
fn json_type_name(v: &Value) -> &'static str {
    match v {
        Value::Null => "null",
        Value::Bool(_) => "boolean",
        Value::Number(_) => "number",
        Value::String(_) => "string",
        Value::Array(_) => "array",
        Value::Object(_) => "object",
    }
}

pub async fn handle_evaluate(
    adapter: &EngineAdapter,
    params: Value,
) -> Result<Value, (StatusCode, Value)> {
    let span = tracing::info_span!(
        "tool.evaluate",
        script_len = tracing::field::Empty,
        tier = tracing::field::Empty,
        elapsed_ms = tracing::field::Empty,
        timed_out = false
    );
    async move {
        let p: EvaluateParams = serde_json::from_value(params).map_err(|e| {
        (
            StatusCode::BAD_REQUEST,
            json!({ "error": { "code": "invalid_params", "message": e.to_string() } }),
        )
    })?;

    // timeout_ms is accepted in the schema but QuickJS enforces its own 10s hard
    // limit via the interrupt handler. We surface it in the error message if provided.
    let _timeout_ms = p.timeout_ms;

    tracing::Span::current().record("script_len", p.script.len() as u64);
    tracing::Span::current().record("tier", "tier1");
    let start = std::time::Instant::now();

    let tree = {
        let page = adapter.get_page().await.ok_or_else(|| {
            (
                StatusCode::BAD_REQUEST,
                json!({ "error": { "code": "no_page_loaded", "message": "no page loaded" } }),
            )
        })?;
        page.tree.clone()
    };

    let mut session = adapter.tier1.acquire().await.map_err(|_| {
        metrics::CIRCUIT_BREAKER_TRIPS_TOTAL
            .with_label_values(&["tier1"])
            .inc();
        (
            StatusCode::SERVICE_UNAVAILABLE,
            json!({ "error": { "code": "session_pool_exhausted", "message": "tier1 pool exhausted" } }),
        )
    })?;

    metrics::JS_RUNTIMES_USED.inc();

    session.attach_dom(tree).await;

    let raw = match session.eval(&p.script).await {
        Ok(v) => v,
        Err(e) => {
            metrics::JS_RUNTIMES_USED.dec();
            adapter.tier1.release_after_use(session);
            // The interrupt handler terminates scripts and the error surfaces
            // as JsEvaluation with "interrupted" in the message rather than
            // a distinct JsTimeout variant from this eval path.
            let message = e.to_string();
            let lower = message.to_lowercase();
            let elapsed = start.elapsed();
            let timed_out = lower.contains("interrupt")
                || elapsed >= Duration::from_millis(JS_EVAL_TIMEOUT_MS);
            let (code, destroy_session) = if timed_out {
                tracing::Span::current().record("timed_out", true);
                ("js_timeout", true)
            } else if lower.contains("out of memory")
                || lower.contains("memory limit")
                || lower.contains("oom")
                || lower.contains("allocation failed")
                || lower.contains("exception generated by quickjs")
            {
                ("js_out_of_memory", true)
            } else {
                ("js_error", false)
            };
            if destroy_session {
                let _ = adapter.broker.remove(adapter.session_uuid);
                if adapter.session_active.swap(false, AtomicOrdering::AcqRel) {
                    metrics::SESSIONS_ACTIVE.dec();
                }
            }
            tracing::Span::current().record("elapsed_ms", elapsed.as_millis() as u64);
            return Err((
                StatusCode::INTERNAL_SERVER_ERROR,
                json!({ "error": { "code": code, "message": message } }),
            ));
        }
    };

    metrics::JS_RUNTIMES_USED.dec();
    adapter.tier1.release_after_use(session);

    // Try to parse the result string as a JSON value. If it succeeds, carry the
    // type through the type-name helper. If not, fall back to raw string output.
    let (result_val, type_str) = match serde_json::from_str::<Value>(&raw) {
        Ok(parsed) => {
            let type_name = json_type_name(&parsed);
            (parsed, type_name)
        }
        Err(_) => (Value::String(raw), "string"),
    };

    let elapsed = start.elapsed();
    metrics::JS_EVALUATION_DURATION_SECONDS
        .with_label_values(&["tier1"])
        .observe(elapsed.as_secs_f64());
    if let Err(err) = adapter.enforce_budget_usage(
        result_val.to_string().len(),
        elapsed.as_millis() as u64,
        0,
    ) {
        return Err((
            StatusCode::TOO_MANY_REQUESTS,
            json!({ "error": { "code": "budget_exceeded", "message": err.to_string() } }),
        ));
    }

    tracing::Span::current().record("elapsed_ms", elapsed.as_millis() as u64);

    Ok(json!({
        "result": result_val,
        "type":   type_str,
    }))
    }
    .instrument(span)
    .await
}
